### ISSUE TITLE
Can we also add different sensors and libraries around them to this list?

### ISSUE THREAD

**Issue by baali** [openaq/awesome-air-quality#4]
Or is it meant just for libraries that handles AQI data? I was not able figure it out after reading the [submission guidelines](https://github.com/openaq/awesome-air-quality/blob/main/contributing.md).

**Comment by russbiggs** [comment]
Currently we're gathering open source packages/libraries around air quality, can you share the package you're considering and we can see if/how it might fit in the list? I think I need more info to better understand

**Comment by baali** [comment]
I was referring to libraries that work with Sensors. For example, [here is library](https://github.com/Silvan85/Nova_SDS011) that would work with [Nova SDS011 sensor](https://aqicn.org/sensor/sds011/). Similarly there are other libraries that work with this sensor. One could even read data from Serial port directly. 

And then, there are other sensors also, like [Plantower](https://aqicn.org/sensor/pms5003-7003/) series. [GP2Y1010AU0F](https://in.element14.com/sharp/gp2y1010au0f/sensor-dust-optical/dp/9707956) dust sensor from Sharp. 

Do you think this [awesome list](https://github.com/topics/awesome-list) would include everything involving quantifying Air Quality(hardware, libraries, APIs, platforms)?

**Comment by russbiggs** [comment]
That library seem like it would fit into this list! in the future we could maybe break out a separate section for hardware specific/firmware types of tools but for now it works in the main list.  If you would to add it open a PR, add a new section for C++ and place it under that. Thanks!
